# Generated by Django 5.2 on 2025-08-24 14:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('NewApp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=20, verbose_name='name')),
                ('password', models.CharField(max_length=100, verbose_name='password')),
                ('email', models.CharField(verbose_name='email')),
            ],
        ),
    ]
