# Generated by Django 5.2 on 2025-08-24 15:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('NewApp', '0002_user'),
    ]

    operations = [
        migrations.DeleteModel(
            name='User',
        ),
    ]
